### ISSUE TITLE
Ask for the count data

### ISSUE THREAD

**Issue by ChristopherLeeZG** [piquelab/sclabor#1]
Hello, I am concerned that your paper has been accepted by the elife magazine. 
May I ask you for count data of those single-cell RNAseq data? I am working on single-cell RNA seq of Placenta in patients with eclampsia and would like to refer to your paper.  I have waited for two months, but the **phs001886.v1.p1** is not yet available.
I will be very grateful to you. Thanks!
my email address : followinggodlee@gmail.com

**Comment by rpique** [comment]
The dbGaP site is in process to being released to the public. 
https://www.ncbi.nlm.nih.gov/gap/study/status/35939
They told me that the last step will take about 3 days.

**Comment by ChristopherLeeZG** [comment]
Thank you very much!
